"""Parse Gmail action-reply messages into typed ``ParsedAction`` records.

The reply emails are generated by the ``mailto:`` action links in
``pulse/mailer.py``. Their subject follows a fixed shape::

    "<ACTION> pulse_<id> <token>"      e.g. "SENT pulse_2026-05-22-henry ab8b..."

This module:

* Splits the subject, validates the action verb, and runs the HMAC
  through ``pulse.links.verify_action`` so a forged reply can't poison
  state.
* For EDITED replies, extracts the rep's edited text from the body
  (everything after the ``Paste the final text...`` prompt).
* Returns either ``ParsedAction`` (good) or ``InvalidAction`` (rejected),
  so the caller can log diagnostics rather than crashing on malformed
  inputs.

Pure functions, no I/O.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from pulse.links import (
    ACTION_EDITED,
    ACTION_REASSIGN,
    ACTION_SENT,
    ACTION_SKIPPED,
    KNOWN_ACTIONS,
    verify_action,
)

EDITED_BODY_PROMPT = "Paste the final text you sent below:"
SKIPPED_BODY_PROMPT = "Reason (optional):"
REASSIGN_BODY_PROMPT_PREFIX = "Reassign to:"

# Strips leading "Re: " / "Fwd: " / "RE: " etc. that some mail clients prepend
# even when the user opens via a mailto: link. Belt-and-suspenders — the action
# links create fresh messages, but reps sometimes hit reply-all by accident.
_REPLY_PREFIX_RE = re.compile(r"^(re|fwd|fw)\s*:\s*", re.IGNORECASE)


@dataclass(frozen=True)
class ParsedAction:
    """A verified, well-formed action reply ready to record."""

    action: str  # one of pulse.links.KNOWN_ACTIONS
    pulse_id: str  # e.g. "2026-05-22-henry" — caller looks up rep/customer
    token: str  # HMAC, already verified
    sender: str  # raw From header (for audit logs)
    edited_text: str | None  # populated when action == ACTION_EDITED
    skip_reason: str | None  # populated when action == ACTION_SKIPPED


@dataclass(frozen=True)
class InvalidAction:
    """Why a message couldn't be processed. Caller logs + skips."""

    reason: str  # short stable key — e.g. "bad_subject", "bad_token"
    detail: str  # human-readable elaboration
    raw_subject: str


# ---- helpers ---------------------------------------------------------------


def _strip_reply_prefix(subject: str) -> str:
    """Strip up to three nested ``Re:``/``Fwd:`` prefixes."""
    out = subject.strip()
    for _ in range(3):
        new = _REPLY_PREFIX_RE.sub("", out, count=1).strip()
        if new == out:
            break
        out = new
    return out


def _extract_after_prompt(body: str, prompt: str) -> str:
    """Return everything after the first occurrence of ``prompt``, stripped.

    If the prompt isn't found, returns the whole body stripped — handles
    the case where the rep deleted the prompt before typing.
    """
    idx = body.find(prompt)
    if idx < 0:
        return body.strip()
    return body[idx + len(prompt) :].strip()


# ---- main entry ------------------------------------------------------------


def parse_subject(subject: str) -> tuple[str, str, str] | None:
    """Return ``(action, pulse_id, token)`` or ``None`` on malformed input.

    Subject shape: ``"<ACTION> pulse_<id> <token>"``. ``<id>`` itself may
    contain hyphens (it's ``YYYY-MM-DD-<rep_id>``), so we split on
    whitespace and rely on the fixed positions of action/prefix/token.
    """
    cleaned = _strip_reply_prefix(subject)
    parts = cleaned.split()
    # Minimum: 3 tokens (action, pulse_<id>, token).
    expected_token_count = 3
    if len(parts) < expected_token_count:
        return None
    action_raw = parts[0].lower()
    pulse_marker = parts[1]
    token = parts[2]
    if action_raw not in KNOWN_ACTIONS:
        return None
    if not pulse_marker.startswith("pulse_"):
        return None
    pulse_id = pulse_marker[len("pulse_") :]
    if not pulse_id:
        return None
    return action_raw, pulse_id, token


def parse_message(
    subject: str,
    body: str,
    sender: str,
    *,
    secret: bytes,
) -> ParsedAction | InvalidAction:
    """Validate + project a Gmail message into a ``ParsedAction``.

    Failure modes (returned as ``InvalidAction``):
    * ``bad_subject`` — couldn't extract action/pulse_id/token
    * ``bad_token`` — HMAC didn't verify (forged or tampered)
    """
    parsed = parse_subject(subject)
    if parsed is None:
        return InvalidAction(
            reason="bad_subject",
            detail="subject doesn't match '<ACTION> pulse_<id> <token>'",
            raw_subject=subject,
        )
    action, pulse_id, token = parsed
    if not verify_action(secret, action, pulse_id, token):
        return InvalidAction(
            reason="bad_token",
            detail="HMAC verification failed — forged, tampered, or wrong secret",
            raw_subject=subject,
        )

    edited_text: str | None = None
    skip_reason: str | None = None
    if action == ACTION_EDITED:
        edited_text = _extract_after_prompt(body, EDITED_BODY_PROMPT) or None
    elif action == ACTION_SKIPPED:
        skip_reason = _extract_after_prompt(body, SKIPPED_BODY_PROMPT) or None
    elif action in (ACTION_SENT, ACTION_REASSIGN):
        # No body fields to extract; ACTION_REASSIGN's body has the suggested
        # rep but it's already encoded in the mailto template and the inbox
        # poller MVP doesn't act on reassignment routing yet.
        pass

    return ParsedAction(
        action=action,
        pulse_id=pulse_id,
        token=token,
        sender=sender,
        edited_text=edited_text,
        skip_reason=skip_reason,
    )
